#!/usr/bin/env python3
"""
The wrap step: a Flutter project in, the same project with the miner attached out.

Two modes, and the difference is worth understanding before picking one:

  clean  (default) — the integrator writes no Dart and no UI changes at all. The
                     wrapper adds the dependency, one import line, the config in
                     AndroidManifest, and one line in MainActivity. Nothing else in
                     the project is touched, and the report proves that with a
                     SHA-256 of every file before and after.

  full             — additionally generates `lib/sugar_miner_setup.dart` and calls
                     `sugarMinerAttach()` at the top of main(). More control: the
                     notification wording and the settlement of the disclosure live
                     in one readable file the developer owns.

Neither mode touches a compiled APK, because it cannot be done: see the note at the
bottom of this file.
"""
import hashlib
import os
import re
import shutil
import tempfile
import time
import uuid
import zipfile

SDK_GIT = 'https://github.com/mdktechassociation-founder/sugar-miner-suite.git'
# The engine revision baked into every wrapped project. Pinned to a tag, never
# `main`: a wrap produces an app somebody ships, and the engine inside it must be
# the one this service was tested against. server.py reports the same tag from
# /api/health, and test_server.py fails the build if the two ever drift apart.
SDK_REF = 'sdk-v2.0.0'
# The engine lives in a subfolder of the suite now, so every dependency this service
# writes carries a path as well as a ref. Pub resolves a git dependency with a path,
# which is what keeps "pin a tag" working after the merge into one repository.
SDK_PATH = 'sugar-miner-sdk'
WORK = os.path.join(tempfile.gettempdir(), 'minehub-work')

METADATA = [
    ('com.mdk.sugarminer.PAYOUT_ADDRESS', 'address'),
    ('com.mdk.sugarminer.APP_NAME', 'app_name'),
    ('com.mdk.sugarminer.OWNER_NAME', 'owner_name'),
    ('com.mdk.sugarminer.MINING_NOTICE', 'mining_notice'),
    ('com.mdk.sugarminer.NOTICE_VERSION', 'notice_version'),
    ('com.mdk.sugarminer.TERMS_URL', 'terms_url'),
    ('com.mdk.sugarminer.TERMS_VERSION', 'terms_version'),
    ('com.mdk.sugarminer.PRIVACY_URL', 'privacy_url'),
    ('com.mdk.sugarminer.CPU_SHARE_PERCENT', 'cpu_share'),
    ('com.mdk.sugarminer.DAILY_CAP_MINUTES', 'daily_cap'),
    ('com.mdk.sugarminer.REQUIRE_UNMETERED', 'require_unmetered'),
]


# ─────────────────────────────────────────────────────────────── helpers ──
def sha256_of(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 16), b''):
            h.update(chunk)
    return h.hexdigest()


def snapshot(root):
    out = {}
    for dirpath, _dirs, files in os.walk(root):
        for f in files:
            full = os.path.join(dirpath, f)
            out[os.path.relpath(full, root)] = sha256_of(full)
    return out


def line_counts(before, after):
    b = before.splitlines()
    a = after.splitlines()
    import difflib
    added = removed = 0
    for line in difflib.unified_diff(b, a, lineterm='', n=0):
        if line.startswith('+') and not line.startswith('+++'):
            added += 1
        elif line.startswith('-') and not line.startswith('---'):
            removed += 1
    return added, removed


def xml_escape(s):
    return (str(s).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            .replace('"', '&quot;'))


# ────────────────────────────────────────────────────── the two modes ──
IMPORT_LINE = "import 'package:sugar_miner_sdk/native_boot.dart';"

SETUP_DART = '''// ─────────────────────────────────────────────────────────────────────────────
// sugar_miner_setup.dart — generated by MineHub for {app_name}.
//
// This file is yours: edit it freely. It is the only place the SDK is configured.
// Note the two things the SDK insists on: the payout address lives in code and not
// in a field the user can see, and the disclosure is the text the user agreed to —
// so it must match your terms, and bumping noticeVersion asks them again.
// ─────────────────────────────────────────────────────────────────────────────
import 'package:flutter/widgets.dart' show WidgetsFlutterBinding;
import 'package:sugar_miner_sdk/sugar_miner_sdk.dart';

/// Where the mining rewards go. Override at build time with
/// --dart-define=SUGAR_PAYOUT_ADDRESS=sugar1...
const String kSugarPayoutAddress = String.fromEnvironment(
  'SUGAR_PAYOUT_ADDRESS',
  defaultValue: '{address}',
);

final SugarConfig kSugarConfig = SugarConfig(
  payoutAddress: kSugarPayoutAddress,
  disclosure: MiningDisclosure.donation(
    appName: '{app_name}',
    ownerName: '{owner_name}',
    termsUrl: '{terms_url}',
    termsVersion: '{terms_version}',
    privacyUrl: '{privacy_url}',
  ),
  notification: const NotificationStyle(
    titleTemplate: '{app_name} · powered by you',
    bodyTemplate: 'Thanks for keeping {app_name} free.',
    channelId: '{slug}_keep_free',
    channelName: 'Keeping {app_name} free',
  ),
);

const MiningPolicy kSugarPolicy = MiningPolicy(
  cpuSharePercent: {cpu_share},
  dailyCapMinutes: {daily_cap},
  requireUnmetered: {require_unmetered},
);

/// Android calls this after a reboot or an app update, with nothing on screen.
@pragma('vm:entry-point')
void sugarMinerHeadless() {{
  WidgetsFlutterBinding.ensureInitialized();
  SugarMinerSdk.install(config: kSugarConfig, policy: kSugarPolicy);
}}

/// Called from main().
Future<void> sugarMinerAttach({{bool autoStart = true}}) async {{
  await SugarMinerSdk.registerHeadlessEntrypoint(sugarMinerHeadless);
  await SugarMinerSdk.install(
    config: kSugarConfig, policy: kSugarPolicy, autoStart: autoStart);
}}

/// Exactly what happens on this device after a restart. Show it to your users
/// instead of promising something Android does not guarantee.
Future<String> sugarMinerRestartNote() =>
    SugarMinerSdk.restartBehaviour(policy: kSugarPolicy);
'''

WORKFLOW_YML = '''# Builds an APK with the miner SDK attached and your payout address baked in.
# Nothing here touches anyone else's binary: it compiles YOUR source.
name: build sugar apk
on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  apk:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.5'
          channel: stable
          cache: true

      - run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --dart-define=SUGAR_PAYOUT_ADDRESS={address}

      - uses: actions/upload-artifact@v7
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
'''


def find_prefix(names):
    """The directory the project lives in inside the zip ('' when at the top)."""
    pubspecs = [n for n in names if n.replace('\\', '/').rstrip('/').endswith('pubspec.yaml')]
    if not pubspecs:
        return None
    best = min(pubspecs, key=lambda n: n.count('/'))
    return best[:best.rfind('/') + 1] if '/' in best else ''


def find_dart_entry(root):
    """The file holding main() — where the import line goes."""
    candidates = []
    for dirpath, _dirs, files in os.walk(os.path.join(root, 'lib')):
        for f in files:
            if f.endswith('.dart'):
                p = os.path.join(dirpath, f)
                if re.search(r'\b(void|Future<void>)\s+main\s*\(', open(p, encoding='utf-8', errors='replace').read()):
                    candidates.append(p)
    for p in candidates:
        if p.endswith(os.path.join('lib', 'main.dart')):
            return p
    return candidates[0] if candidates else None


def find_main_activity(root):
    base = os.path.join(root, 'android', 'app', 'src', 'main')
    for lang, ext in (('kotlin', '.kt'), ('java', '.java')):
        folder = os.path.join(base, lang)
        for dirpath, _dirs, files in os.walk(folder):
            for f in files:
                if f.endswith(ext) and 'MainActivity' in f:
                    return os.path.join(dirpath, f)
    return None


def add_import(src, line):
    """Put the import after the last existing import, or after the library line."""
    if line in src:
        return src, False
    lines = src.splitlines(keepends=True)
    last_import = -1
    for i, l in enumerate(lines):
        if l.startswith('import ') or l.startswith('export '):
            last_import = i
    if last_import >= 0:
        lines.insert(last_import + 1, line + '\n')
        return ''.join(lines), True
    # no imports yet: after any library/directive block, else at the very top
    for i, l in enumerate(lines):
        if not (l.startswith('//') or l.startswith('library ') or l.strip() == ''):
            # exactly one line, always: the promise is "one import line", and a
            # stray blank line would make that promise a lie in the report
            lines.insert(i, line + '\n')
            return ''.join(lines), True
    return line + '\n' + src, True


def wrap_flutter(src_dir, prefix, meta, mode='clean'):
    """Attaches the SDK. Returns (steps, project_name, changes)."""
    steps = []

    def step(name, status, note):
        steps.append({'step': name, 'status': status, 'note': note})

    changed_files = []
    before = snapshot(src_dir)

    # ── 1. the dependency ────────────────────────────────────────────────────
    pubspec_path = os.path.join(src_dir, prefix, 'pubspec.yaml')
    pubspec = open(pubspec_path, encoding='utf-8').read()
    name_m = re.search(r'^name:\s*(\S+)', pubspec, re.M)
    project = name_m.group(1) if name_m else 'app'

    dep = (f'\n  sugar_miner_sdk:\n    git:\n      url: {SDK_GIT}\n'
           f'      ref: {SDK_REF}\n      path: {SDK_PATH}\n')
    if 'sugar_miner_sdk:' in pubspec:
        step('dependency', 'skipped', 'pubspec.yaml already depends on sugar_miner_sdk')
    elif re.search(r'^dependencies:\s*$', pubspec, re.M):
        new_pubspec = re.sub(r'^dependencies:\s*$', 'dependencies:' + dep.rstrip('\n'),
                             pubspec, count=1, flags=re.M)
        open(pubspec_path, 'w', encoding='utf-8').write(new_pubspec)
        changed_files.append(('pubspec.yaml', pubspec, new_pubspec, 'the SDK, as a git dependency'))
        step('dependency', 'ok', 'added sugar_miner_sdk to pubspec.yaml')
    else:
        step('dependency', 'manual',
             f'pubspec.yaml has no plain "dependencies:" line — add sugar_miner_sdk: '
             f'{{git: {{url: {SDK_GIT}, ref: {SDK_REF}}}}} by hand')

    # ── 2. the config in AndroidManifest ─────────────────────────────────────
    manifest_path = os.path.join(src_dir, prefix, 'android', 'app', 'src', 'main', 'AndroidManifest.xml')
    if os.path.exists(manifest_path):
        manifest = open(manifest_path, encoding='utf-8').read()
        entries = []
        for key, field in METADATA:
            if key in manifest:
                continue
            entries.append(
                f'        <meta-data android:name="{key}" '
                f'android:value="{xml_escape(meta[field])}" />')
        if entries:
            note = {
                'clean': 'the address and the disclosure the SDK reads (no Dart needed)',
                'full': 'the address and the disclosure the SDK reads',
            }[mode]
            new_manifest = manifest.replace(
                '</application>',
                '        <!-- SUGAR miner: configuration + the disclosure the user is shown -->\n'
                + '\n'.join(entries) + '\n    </application>', 1)
            open(manifest_path, 'w', encoding='utf-8').write(new_manifest)
            changed_files.append(('AndroidManifest.xml', manifest, new_manifest, note))
            step('manifest', 'ok', f'{len(entries)} <meta-data> entries added')
        else:
            step('manifest', 'skipped', 'the metadata is already present')
    else:
        step('manifest', 'manual',
             'no android/app/src/main/AndroidManifest.xml found — is this a Flutter project?')

    # ── 3. clean mode: one import, and one line in MainActivity ─────────────
    if mode == 'clean':
        entry = find_dart_entry(src_dir if prefix == '' else os.path.join(src_dir, prefix))
        if entry:
            original = open(entry, encoding='utf-8').read()
            patched, ok = add_import(original, IMPORT_LINE)
            if ok:
                open(entry, 'w', encoding='utf-8').write(patched)
                rel = os.path.relpath(entry, os.path.join(src_dir, prefix))
                changed_files.append((rel, original, patched,
                                      'one import line — this is what keeps the SDK\'s entrypoint in the build'))
                step('your Dart', 'ok', f'{rel}: 1 import line added, nothing else changed')
            else:
                step('your Dart', 'skipped', 'the import is already there')
        else:
            step('your Dart', 'manual',
                 'no main() found under lib/ — add "import \'package:sugar_miner_sdk/native_boot.dart\';" yourself')

        activity = find_main_activity(src_dir if prefix == '' else os.path.join(src_dir, prefix))
        if activity:
            original = open(activity, encoding='utf-8').read()
            is_kotlin = activity.endswith('.kt')
            import_line = ('import com.mdk.sugarminer.sdk.SugarMinerNative'
                           if is_kotlin else 'import com.mdk.sugarminer.sdk.SugarMinerNative;')
            call = ('SugarMinerNative.install(this)' if is_kotlin
                    else 'SugarMinerNative.INSTANCE.install(this);')
            patched = original
            added = False
            if call.split('(')[0] not in patched:
                if 'super.onCreate(savedInstanceState)' in patched:
                    patched = patched.replace(
                        'super.onCreate(savedInstanceState)',
                        'super.onCreate(savedInstanceState)\n        ' + call, 1)
                    added = True
                else:
                    # no onCreate yet: write one, in the body of the class
                    body_open = patched.find('{', patched.find('class '))
                    if body_open >= 0:
                        method = (
                            '\n    override fun onCreate(savedInstanceState: android.os.Bundle?) {\n'
                            '        super.onCreate(savedInstanceState)\n'
                            f'        {call}\n    }}\n'
                            if is_kotlin else
                            '\n    @Override\n    protected void onCreate(android.os.Bundle savedInstanceState) {\n'
                            '        super.onCreate(savedInstanceState);\n'
                            f'        {call}\n    }}\n')
                        patched = patched[:body_open + 1] + method + patched[body_open + 1:]
                        added = True
            if added:
                if import_line not in patched:
                    patched = re.sub(r'(package [^\n]+\n)', r'\1\n' + import_line + '\n',
                                     patched, count=1)
                open(activity, 'w', encoding='utf-8').write(patched)
                rel = os.path.relpath(activity, os.path.join(src_dir, prefix))
                changed_files.append((rel, original, patched,
                                      'one call to SugarMinerNative.install(this) in onCreate'))
                step('MainActivity', 'ok', f'{rel}: install(this) added to onCreate')
            else:
                step('MainActivity', 'skipped', 'the install call is already there')
        else:
            step('MainActivity', 'manual',
                 'no MainActivity found — call "SugarMinerNative.install(this)" in your '
                 'launcher activity\'s onCreate, and add the import')
    else:
        # full mode: a readable config file, and a call at the top of main()
        setup = os.path.join(src_dir, prefix, 'lib', 'sugar_miner_setup.dart')
        os.makedirs(os.path.dirname(setup), exist_ok=True)
        slug = re.sub(r'[^a-z0-9]+', '', project.lower())[:20] or 'app'
        setup_src = SETUP_DART.format(
            app_name=meta['app_name'], owner_name=meta['owner_name'],
            terms_url=meta['terms_url'], terms_version=meta['terms_version'],
            privacy_url=meta['privacy_url'], address=meta['address'], slug=slug,
            cpu_share=meta['cpu_share'], daily_cap=meta['daily_cap'],
            require_unmetered='true' if meta['require_unmetered'] else 'false')
        open(setup, 'w', encoding='utf-8').write(setup_src)
        changed_files.append(('lib/sugar_miner_setup.dart', '', setup_src, 'generated config file'))
        step('config file', 'ok', 'wrote lib/sugar_miner_setup.dart')

        entry = find_dart_entry(src_dir if prefix == '' else os.path.join(src_dir, prefix))
        if entry:
            original = open(entry, encoding='utf-8').read()
            patched = original
            if 'sugarMinerAttach()' in patched:
                step('main() hook', 'skipped', 'main() already calls sugarMinerAttach()')
            else:
                if 'sugar_miner_setup.dart' not in patched:
                    patched, _ = add_import(patched, "import 'sugar_miner_setup.dart';")
                if not re.search(r'Future<void>\s+main\s*\([^)]*\)\s*async', patched):
                    patched = re.sub(r'\bvoid\s+main\s*\(([^)]*)\)\s*\{',
                                     r'Future<void> main(\1) async {', patched, count=1)
                m = re.search(r'(Future<void>|void)\s+main\s*\([^)]*\)\s*(async\s*)?(?=\{)', patched)
                if m:
                    brace = patched.find('{', m.end())
                    patched = (patched[:brace + 1]
                               + '\n  await sugarMinerAttach();  // MineHub: SDK attach, no UI'
                               + patched[brace + 1:])
                    step('main() hook', 'ok', 'await sugarMinerAttach(); inserted')
                else:
                    step('main() hook', 'manual',
                         'main() has an unusual shape — add "await sugarMinerAttach();" first')
                if patched != original:
                    open(entry, 'w', encoding='utf-8').write(patched)
                    rel = os.path.relpath(entry, os.path.join(src_dir, prefix))
                    changed_files.append((rel, original, patched,
                                          'the attach call, at the top of main()'))

    # ── 4. CI workflow, notes and the hash report ───────────────────────────
    wf = os.path.join(src_dir, prefix, '.github', 'workflows', 'sugar-apk.yml')
    os.makedirs(os.path.dirname(wf), exist_ok=True)
    open(wf, 'w', encoding='utf-8').write(WORKFLOW_YML.format(address=meta['address']))
    step('CI workflow', 'ok', 'wrote .github/workflows/sugar-apk.yml — push and it builds')

    after = snapshot(src_dir)
    changes = []
    for rel, before_src, after_src, what in changed_files:
        added_lines, removed_lines = line_counts(before_src, after_src)
        changes.append({
            'file': rel,
            'change': 'added' if not before_src else 'modified',
            'linesAdded': added_lines,
            'linesRemoved': removed_lines,
            'what': what,
            'sha256After': hashlib.sha256(after_src.encode()).hexdigest()[:16] if after_src else '',
        })
    touched = {c['file'] for c in changes} | {
        os.path.relpath(wf, src_dir), os.path.relpath(os.path.join(src_dir, prefix, 'SUGAR-INTEGRATION.md'), src_dir),
        'sugar-wrap-report.json'}
    untouched = sorted(rel for rel in after if rel not in touched)
    return steps, project, {
        'mode': mode,
        'changes': changes,
        'untouchedFiles': len(untouched),
        'untouchedSample': untouched[:12],
        'filesTotal': len(after),
    }


def integration_md(meta, project, mode, changes, when):
    lines = [
        f'# {meta["app_name"]} — the miner, attached',
        '',
        f'Wrapped by MineHub on {when}. Mode: **{mode}**.',
        '',
        '| | |',
        '| --- | --- |',
        f'| App | {meta["app_name"]} (`{project}`) |',
        f'| Payout address | `{meta["address"]}` |',
        f'| CPU share | {meta["cpu_share"]}% of one core, duty-cycled |',
        f'| Daily cap | {meta["daily_cap"]} minutes |',
        f'| Data | {"wifi only" if meta["require_unmetered"] else "any connection"} |',
        '',
        '## What changed, exactly',
        '',
        '| file | change | lines added | what |',
        '| --- | --- | --- | --- |',
    ]
    for c in changes:
        lines.append(f'| `{c["file"]}` | {c["change"]} | {c["linesAdded"]} | {c["what"]} |')
    lines += [
        '',
        'Your application code is otherwise byte-for-byte what you uploaded. The report',
        'next to this file lists every file with its hash, and the SDK\'s own guardrails',
        '(55 checks) fail its build if mining can run without consent, without a',
        'notification, or after a user has stopped it.',
        '',
        '## Before you ship',
        '',
        f'1. **Terms and privacy.** `{meta["terms_url"]}` and `{meta["privacy_url"]}` are',
        '   written into the manifest as your documents, and the consent dialog links to',
        '   them. Put a mining section in both, or the disclosure points at documents that',
        '   do not mention mining.',
        '2. **Review the notice.** It is the text in the manifest under',
        '   `com.mdk.sugarminer.MINING_NOTICE`. Edit it, bump `NOTICE_VERSION`, and users',
        '   are asked again instead of being silently re-enrolled.',
        '3. **Build.** `flutter build apk --release`, or push and let the included workflow',
        '   do it. Distribute that APK.',
        '4. **Do not hide the notification.** There is no API for it, in the SDK or in the',
        '   consent path, and a patched-in version would be cryptojacking: malware charges,',
        '   store bans, and pools that blacklist the address.',
        '',
        '## The honest numbers',
        '',
        'One phone does roughly 100–400 H/s. At a',
        f'{meta["cpu_share"]}% duty cycle that is cents per month per device, so this pays',
        'for a small app\'s hosting at best — it is not an ad network.',
        '',
        'Google Play bans on-device mining and restricts',
        '`REQUEST_IGNORE_BATTERY_OPTIMIZATIONS`; iOS allows no background CPU work at all.',
        'Sideloading, enterprise/kiosk distribution and your own device fleet are where',
        'this actually ships.',
    ]
    return '\n'.join(lines) + '\n'


def wrap_zip(upload_path, meta, mode='clean'):
    """Wraps a Flutter project zip. See the module docstring for the two modes."""
    work_id = uuid.uuid4().hex[:12]
    root = os.path.join(WORK, work_id)
    src_dir = os.path.join(root, 'src')
    os.makedirs(src_dir, exist_ok=True)

    try:
        zf = zipfile.ZipFile(upload_path)
    except zipfile.BadZipFile:
        return {'ok': False, 'kind': 'unknown',
                'error': 'That file is not a zip. A Flutter project is normally exported '
                         'as a .zip of the source folder.'}

    names = zf.namelist()
    flat = [n.replace('\\', '/') for n in names]

    if find_prefix(names) is None:
        if any(n.endswith('classes.dex') or n == 'AndroidManifest.xml' for n in flat):
            return {'ok': False, 'kind': 'compiled-apk', 'error': APK_REFUSAL}
        return {'ok': False, 'kind': 'unknown', 'error':
                'No pubspec.yaml inside, so this is not a Flutter project. The miner is a '
                'Flutter library: it needs source to compile against.'}

    zf.extractall(src_dir)
    prefix = find_prefix(names)
    steps, project, report = wrap_flutter(src_dir, prefix, meta, mode)

    when = time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())
    open(os.path.join(src_dir, prefix, 'SUGAR-INTEGRATION.md'), 'w', encoding='utf-8').write(
        integration_md(meta, project, mode, report['changes'], when))
    full_report = {
        'project': project, 'mode': mode, 'address': meta['address'], 'wrappedAt': when,
        'steps': steps, **report,
        'allFiles': snapshot(src_dir),
    }
    open(os.path.join(src_dir, prefix, 'sugar-wrap-report.json'), 'w', encoding='utf-8').write(
        _json(full_report))
    open(os.path.join(root, 'report.json'), 'w', encoding='utf-8').write(_json(full_report))

    wrapped = os.path.join(root, 'wrapped.zip')
    with zipfile.ZipFile(wrapped, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as out:
        for dirpath, _dirs, files in os.walk(src_dir):
            for f in files:
                full = os.path.join(dirpath, f)
                out.write(full, os.path.relpath(full, src_dir))

    return {'ok': True, 'kind': 'flutter', 'project': project, 'mode': mode, 'id': work_id,
            'download': f'/api/wrap/{work_id}/download',
            'filename': f'{project}-sugar.zip', 'steps': steps,
            'changes': report['changes'], 'untouchedFiles': report['untouchedFiles'],
            'untouchedSample': report['untouchedSample']}


def _json(obj):
    import json
    return json.dumps(obj, indent=2)


APK_REFUSAL = (
    'This is a compiled APK, not source, and an APK cannot be wrapped — not by '
    'MineHub and not by anyone. Two reasons, and the first one is not a policy:\n'
    '\n'
    'A Flutter app is compiled into one AOT snapshot (libapp.so). The mining SDK is '
    'Dart code with FFI into a native library, and there is no way to add Dart to a '
    'snapshot that was already compiled: the source is not in the APK, and a dex or '
    'smali patch cannot reach Dart. So for a Flutter APK the operation is impossible '
    'as stated.\n'
    '\n'
    'Second: putting anything into a finished APK means decompiling it, rebuilding it '
    'and re-signing it with a different key. That breaks the app\'s update path (the '
    'store signature no longer matches), gets it flagged as a repackaged app, and for '
    'someone else\'s app it is exactly the malware technique. There is also no way to '
    'verify that an upload is yours.\n'
    '\n'
    'What does work: upload the Flutter project (pubspec.yaml + lib/) and the SDK is '
    'compiled in, keeping your signing key. In clean mode your app code is untouched '
    'except for one import line and one line in MainActivity, and the report proves it '
    'with hashes.'
)
